/// <filename>
///     AddRecord.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class AddRecord : ZES.Infrastructure.Domain.Command
  {
    public AddRecord() 
    {
    }  
    public double RecordValue
    {
       get; 
       set;
    }  
    public AddRecord(string target, double recordValue)
    {
      RecordId = target;
      RecordValue = recordValue;
    }
    
    public string RecordId { get; set; }
    public override string Target => RecordId;
  }
}

