/// <filename>
///     AddRecordHandler.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class AddRecordHandler : ZES.Infrastructure.Domain.CommandHandlerBase<AddRecord, Record>
  {
    public AddRecordHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Record record, AddRecord command)
    {
      record.Root(command.RecordValue, command.Timestamp);
    }
  }
}

