/// <filename>
///     AddRootDetails.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class AddRootDetails : ZES.Infrastructure.Domain.Command
  {
    public AddRootDetails() 
    {
    }  
    public string[] Details
    {
       get;
    }  
    public AddRootDetails(string target, string[] details)
    {
      RootId = target;
      Details = details;
    }

    public string RootId { get; set; }

    public override string Target => RootId;
  }
}

