/// <filename>
///     AddRootDetailsHandler.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class AddRootDetailsHandler : ZES.Infrastructure.Domain.CommandHandlerBase<AddRootDetails, Root>
  {
    public AddRootDetailsHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Root root, AddRootDetails command)
    {
      root.AddDetails(command.Details);
    }
  }
}

