/// <filename>
///     CreateRecordHandler.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class CreateRecordHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateRecord, Record>
  {
    public CreateRecordHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Record Create (CreateRecord command)
    {
      return new Record(command.Target);
    }
  }
}

