/// <filename>
///     CreateRecordHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace ZES.Tests.Domain.Commands
{
  public class CreateRecordHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateRecord, Record>
  {
    public CreateRecordHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Record Create (CreateRecord command)
    {
      return new Record(command.Target);
    }
  }
}

