/// <filename>
///     CreateRoot.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class CreateRoot : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public CreateRoot() 
    {
    }  
    public CreateRoot(string target) : base(target) 
    {
    }
  }
}

