/// <filename>
///     CreateRootHandler.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class CreateRootHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateRoot, Root>
  {
    public CreateRootHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Root Create (CreateRoot command)
    {
      return new Root(command.Target);
    }
  }
}

