/// <filename>
///     CreateRootHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace ZES.Tests.Domain.Commands
{
  public class CreateRootHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateRoot, Root>
  {
    public CreateRootHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Root Create (CreateRoot command)
    {
      return new Root(command.Target);
    }
  }
}

