/// <filename>
///     CreateRecord.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class CreateRecord : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public CreateRecord() 
    {
    }  
    public CreateRecord(string target) : base(target) 
    {
    }
  }
}

