/// <filename>
///     UpdateRoot.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class UpdateRoot : ZES.Infrastructure.Domain.Command
  {
    public UpdateRoot() 
    {
    }  
    public UpdateRoot(string target)
    {
        RootId = target;
    }
    
    public string RootId { get; set; }
    public override string Target => RootId;
  }
}

