/// <filename>
///     UpdateRoot.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Commands
{
  public class UpdateRoot : ZES.Infrastructure.Domain.Command
  {
    public UpdateRoot() 
    {
    }  
    public UpdateRoot(string target) : base(target) 
    {
    }
  }
}

