version: 1.0.{build}
image: Visual Studio 2017

before_build:
  - cmd: dotnet restore --verbosity m
build:
  project: ZES.sln
  verbosity: minimal
test_script:
  - cmd: dotnet test ZES.Tests\ZES.Tests.csproj
on_failure:
  #- cmd: 7z a SqlTests.zip Chronos.Tests\bin\Debug\netcoreapp2.0\*.db
  #- cmd: appveyor PushArtifact SqlTests.zip
  # Cache node modules, and refresh if package.json changes
cache:
  #- node_modules -> package.json
artifacts:
  #- path: SqlTests.zip
  #  name: SqlTests
