// <auto-generated/>
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using SimpleInjector;
using ZES.Interfaces;
using ZES.Interfaces.Pipes;
using ZES.Tests.Domain;
using ZES.Tests.Domain.Commands;
using ZES.Tests.Domain.Queries;
using ZES.Utils;

namespace ZES.Perf
{
    public static class Program
    {
        public static void Main()
        {
            Run().Wait();
        }

        private static Container CreateContainer()
        {
            var container = new Container();
            container.Options.DefaultLifestyle = Lifestyle.Singleton;
            var config = Logging.NLog.Configure();
            Logging.NLog.Enable(config);

            var root = new CompositionRoot();
            root.ComposeApplication(container);
            container.Register<IServiceCollection>(() => new ServiceCollection(), Lifestyle.Singleton);

            Config.RegisterCommands(container);
            Config.RegisterQueries(container);
            Config.RegisterProjections(container);

            //container.Verify();
            root.Verify(container);
            return container;
        }

        private static async Task Run()
        {
            var container = CreateContainer();
            var bus = container.GetInstance<IBus>();
            const int numRoots = 10000;
            var log = container.GetInstance<ILog>();
            var t = Stopwatch.StartNew();
            var rootId = numRoots;
            while (rootId > 0)
            {
                var command = new CreateRoot($"Root{rootId}");
                await bus.CommandAsync(command);
                rootId--;
            }

            var statsQuery = new StatsQuery();
            await bus.QueryUntil(statsQuery, s => s?.NumberOfRoots == numRoots, TimeSpan.FromSeconds(numRoots / 1000.0));
            log.Info($"Total time : {t.ElapsedMilliseconds}, per root : {(float)t.ElapsedMilliseconds / numRoots}");
        }
    }
}