/// <filename>
///     RootDetailsAdded.cs
/// </filename>

// <auto-generated/>

namespace ZES.Tests.Domain.Events
{
  public class RootDetailsAdded : ZES.Infrastructure.Domain.Event
  {
    public RootDetailsAdded() 
    {
    }
    
    public string[] Details
    {
       get; 
       set;
    }  
    public RootDetailsAdded(string[] details) 
    {
      Details = details;
    }
  }
}

