/// <filename>
///     TotalRecord.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Queries
{
  public class TotalRecord : ZES.Interfaces.Domain.IState
  {
    public TotalRecord() 
    {
    }  
    public double Total
    {
       get; 
       set;
    }  
    public TotalRecord(double total) 
    {
      Total = total;
    }
  }
}

