/// <filename>
///     TotalRecordQuery.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Queries
{
  public class TotalRecordQuery : ZES.Infrastructure.Domain.Query<TotalRecord>
  {
    public TotalRecordQuery() 
    {
    }
  }
}

