/// <filename>
///     TotalRecordHandler.cs
/// </filename>

// <auto-generated/>
 namespace ZES.Tests.Domain.Queries
{
  public class TotalRecordHandler : ZES.Interfaces.Domain.IProjectionHandler<TotalRecord,ZES.Tests.Domain.Events.RootRecorded>
  {
    public TotalRecord Handle (ZES.Interfaces.IEvent e, TotalRecord state)
    {
      Handle(e as ZES.Tests.Domain.Events.RootRecorded, state);; 
      return state;
    }  
    public TotalRecord Handle (ZES.Tests.Domain.Events.RootRecorded e, TotalRecord state)
    {
      lock (state)
      {
        state.Total += e.RecordValue;
      }

      return state;
    }
  }
}

